### ISSUE TITLE
Come up with better name

### ISSUE THREAD

**Issue by jchck** [jchck/thyme#1]
@mattcdowning come up with like 5 awesome names for us to choose from

**Comment by jchck** [comment]
also, use that name throughout the site as needed

**Comment by mattcdowning** [comment]
@jchck Like any of these?
1. PostSage
2. TachPress
3. FunctionalSage
4. SageNext
5. FutureSage
6. Post-Future-Sage
7. TPS (Tachyons, PostCSS, Sage)
8. UnSage
9. SlimmerSage

**Comment by jchck** [comment]
I'm lukewarm on TachPress & TPS.

The rest seem to (to varying degrees) editorialize Sage which I'm not too hot on. i.e.: if we're "FunctionalSage" and we're a fork of Sage, are we implying we're more functional than Sage?

I like where your head's at with PostSage since we're Sage+PostCss but I'm hesitant to go with that since the double entendre: post as in beyond and post as in PostCss.

What if we did a playful nod to Sage by following the Roots dirt/earthy/plants naming pattern? This could show we're related to but different from Sage, play well with the Roots community, and be compatible with Trellis, Bedrock, Soil.

I guess that would mean a plant or herb name.

**Comment by mattcdowning** [comment]
Agreed on all counts. Any of these stand out?
1. FreshSage
2. Salvia officinalis (scientific name for Sage)
3. SageNext
4. SlimSage
5. ClayPress
6. BabySage
7. GrowthPress
8. PressedSage
9. StemPress
10. Chlorophyll
11. SimpleSage
12. SageBass
13. AtomicSage
14. HerbPress
15. FunctionalPress - this would downplay Sage and emphasize the Functional CSS integration into WP
16. BloomPress
17. BurnPress
18. Stem
19. PerennialPress

**Comment by jchck** [comment]
If we're going to follow the Roots naming convention then we should go with the name of an actual plant. 

No *Press, no *Sage.

- Buchu
- Sorrel
- Basil

I think short, one syllable, easy to spell.

**Comment by jchck** [comment]
**Thyme** 

Fits the Roots naming pattern AND is a nod to Tachyons being faster than light.

**Comment by mattcdowning** [comment]
Thyme works for me! I'll update the Readme.

**Comment by mattcdowning** [comment]
PR made: https://github.com/jchck/project-x/pull/10
