### ISSUE TITLE
'gulp' and 'gulp watch' tasks do not process CSS files or initiate livereload on save

### ISSUE THREAD

**Issue by mattcdowning** [jchck/thyme#13]
**What is the current behavior?**
Upon saving, 'gulp' and  'gulp watch' tasks are not processing CSS files nor livereloading.

**What is the expected or desired behavior?**

CSS preprocessing with livereload via BrowserSync.

## Bug report

**Local environment:**

WordPress version: 4.5.3

OS: OS X Yosemite

NPM/Node version: 3.7.5/5.7.0

**Where did the bug happen? Development or remote servers?**
Development

**Comment by jchck** [comment]
were any errors returned upon running `npm install`?

**Comment by jchck** [comment]
I'm having a hard time recreating this with.

node -v 5.7.0
npm -v 3.10.5

**Comment by mattcdowning** [comment]
PR made https://github.com/jchck/thyme/pull/14. The issue was that Gulp was not configured correctly to watch CSS files.
